version: "3"

services:
  db:
    container_name: resume-db
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_DB: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_USER: postgress
    volumes:
      - resume_database_data:/var/lib/postgresql/data

  web:
    container_name: resume-web
    # image: 127.0.0.1:5000/resume-web
    build: ../server-api
    volumes:
      - ../dist/resume:/home/node/static-web
    environment:
      PGHOST: db
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
        reservations:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    links:
      - db
    ports:
      - "4280:4280"

volumes:
  resume_database_data:
    driver: local

