#!/bin/bash

# Purpose:
#   Stop and remove a Docker Compose group of containers.

# Start from directory, or bust
cd "${BASH_SOURCE%/*}" || exit

echo
echo "Please note: Warnings about 'deploy' and Docker swarm are acceptable."
echo "             As well as 'Network docker_default not found.'"
echo

docker-compose down
