DROP VIEW IF EXISTS vw_person CASCADE;

DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS resume CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS internal_employee_type CASCADE;
DROP TABLE IF EXISTS internal_employee_status CASCADE;
DROP TABLE IF EXISTS degree CASCADE;
DROP TABLE IF EXISTS schooling_level CASCADE;
DROP TABLE IF EXISTS security_clearance CASCADE;
DROP TABLE IF EXISTS resume_source CASCADE;
DROP TABLE IF EXISTS status_of_person CASCADE;

DROP TABLE IF EXISTS changelog;
-- DROP DATABASE postgres;
